<?php
/**
 * @author: Ignacio Cruz (igmoweb)
 * @version: 1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * @todo replace
 */
if ( class_exists( 'Plugin_Name_Admin_Page' ) ) {
	/**
	 * @todo replace
	 * Class Plugin_Name_Admin_Page
	 *
	 * Serves as template for all admin pages
	 */
	/**
	 * @todo replace
	 */
	class Plugin_Name_Admin_Page {

		/**
		 * Page unique slug
		 *
		 * @var string
		 */
		protected $slug = '';

		/**
		 * Page unique ID generated by WordPress
		 *
		 * @var null|string
		 */
		public $page_id = null;

		/**
		 * @todo replace
		 * Plugin_Name_Admin_Page constructor.
		 *
		 * @param string $slug Unique page slug
		 * @param string $page_title
		 * @param string $menu_title
		 * @param string $cap WordPress capability
		 * @param bool|string $parent Parent page slug. False if is not a child
		 * @param bool|string $icon Icon for the page
		 */
		public function __construct( $slug, $page_title, $menu_title, $cap, $parent = false, $icon = false ) {
			$this->slug = $slug;

			if ( ! $parent ) {
				$this->page_id = add_menu_page(
					$page_title,
					$menu_title,
					$cap,
					$slug,
					array( $this, 'render' )
				);
			}
			else {
				$this->page_id = add_submenu_page(
					$parent,
					$page_title,
					$menu_title,
					$cap,
					$slug,
					array( $this, 'render' )
				);
			}


			add_action( 'load-' . $this->page_id, array( $this, 'on_load' ) );
			add_filter( 'load-' . $this->page_id, array( $this, 'add_screen_hooks' ) );
		}

		/**
		 * This function is executed in every load of this admin page. Overriden in child classes
		 */
		public function on_load() {	}

		/**
		 * Executed in every load. Add your hooks for this screen here
		 */
		public function add_screen_hooks() {}

		/**
		 * Displays the page. Can be overriden in child classes
		 *
		 * By default, it loads views/$slug-page.php file
		 */
		protected function display() {
			/**
			 * @todo replace
			 */
			plugin_name_load_admin_view( "{$this->slug}-page" );
		}

		/**
		 * Render the page
		 */
		public function render() {
			// @todo replace
			?>
			<div id="container" class="wrap wrap-<?php echo esc_attr( plugin_name_slug() ); ?>">
				<?php $this->display(); ?>
			</div><!-- end container -->
			<?php
		}
	}
}

